Repository Interacao-Humano-Computador/2020.1-BCE, pull requests merged in 2020-11, with the labels that each got.

#111 Avaliação do protótipo de baixa fidelidade
  docs/_coverpage.md
  docs/_sidebar.md
  docs/pages/ponto_de_controle_5/entrevistas_prototipo.md
Labels: documentation

#110 Avaliação dos storyboards
  docs/_sidebar.md
  docs/pages/ponto_de_controle_4/analise_tarefa_v2.md
  docs/pages/ponto_de_controle_4/apresentacao.md
  docs/pages/ponto_de_controle_4/entrevistas.md
  docs/pages/ponto_de_controle_4/plan_aval_storyboard.md
  docs/pages/ponto_de_controle_4/planejamento_1_entrevista.md
  docs/pages/ponto_de_controle_4/storyboard.md
  docs/pages/ponto_de_controle_4/termo_de_consentimento.md
  docs/pages/ponto_de_controle_5/avaliacao_storyboard.md
  docs/pages/ponto_de_controle_5/low_fidelity_prototype.md
  docs/pages/ponto_de_controle_5/plan_aval_prototipo_baixa_fidelidade.md
  docs/pages/ponto_de_controle_5/termo_de_consentimento.md
Labels: documentation

#122 Planejamento da avaliação - Protótipo de Alta fidelidade
  docs/_media/assets/detalhes-sobre-livro-2.png
  docs/_media/assets/termo-de-consentimento-4.png
  docs/_media/images/plan_aval/ian-sommerville-software-engineering-9th.jpg
  docs/_sidebar.md
  docs/index.html
  docs/pages/ponto_de_controle_6/TERMO DE CONSENTIMENTO Protótipos Alta.pdf
  docs/pages/ponto_de_controle_6/plan_aval_prot_alta_fidelidade_entrevistas.md
  docs/pages/ponto_de_controle_6/plan_aval_prototipo_alta_fidelidade.md
  docs/pages/ponto_de_controle_6/termo_de_consentimento.md
Labels: documentation

#123 Refatorar sidebar
  docs/_sidebar.md
  docs/pages/ponto_de_controle_1/planejamento_projeto.md
  docs/pages/ponto_de_controle_2/planejamento_do_questionario.md
Labels: bug-fix, enhancement

#124 Second time refactoring sidebar
  docs/_sidebar.md
  docs/index.html
Labels: bug-fix

#132 Avaliação do protótipo alta fidelidade - 1 etapa
  docs/_sidebar.md
  docs/pages/ponto_de_controle_6/aval_prot_alta_fidelidade_1_etapa.md
  docs/pages/ponto_de_controle_6/plan_aval_prototipo_alta_fidelidade.md
Labels: documentation
