Repository Interacao-Humano-Computador/2020.1-BCE, pull requests merged in 2020-09, with the labels that each got.

#16 Criação do documento de metodologia
  docs/assets/images/print_screen/enquete_1.jpg
  docs/metodologia_do_projeto.md
  docs/reunioes/reuniao_2_set_2020.md
Labels: documentation

#19 Feature/8 website choice
  docs/escolha_site.md
Labels: documentation

#18 Feature/10 documento ferramentas
  docs/index.md
Labels: documentation

#32 Documentar processo de design
  docs/images/ciclo_cenarios.png
  docs/images/ciclo_comunicacao.png
  docs/images/ciclo_estrela.png
  docs/images/ciclo_mayhew.png
  docs/images/ciclo_objetivos.png
  docs/processo_design.md
Labels: documentation

#36 Feature/35 GitHub pages migration
  .gitignore
  docs/.nojekyll
  docs/README.md
  docs/_coverpage.md
  docs/_media/assets/css/base.css
  docs/_media/assets/css/bootstrap.min.css
  docs/_media/assets/images/equipe/durval.jpg
  docs/_media/assets/images/equipe/geraldo.jpg
  docs/_media/assets/images/equipe/isabella.jpg
  docs/_media/assets/images/equipe/joao.jpg
  docs/_media/assets/images/equipe/rafaela.jpg
  docs/_media/assets/images/logos/BCE.jpg
  docs/_media/assets/images/logos/drive.png
  docs/_media/assets/images/logos/github.png
  docs/_media/assets/images/logos/jitsi.png
  docs/_media/assets/images/logos/telegram.png
  docs/_media/assets/images/logos/zenhub.png
  docs/_media/assets/images/print_screen/cronograma.png
  docs/_media/assets/images/print_screen/enquete_1.jpg
  docs/_media/assets/images/print_screen/heatmap.png
  docs/_media/equipe/durval.jpg
  docs/_media/equipe/geraldo.jpg
  docs/_media/equipe/isabella.jpg
  docs/_media/equipe/joao.jpg
  docs/_media/equipe/rafaella.jpg
  docs/_media/favicon.ico
  docs/_media/images/ciclo_cenarios.png
  docs/_media/images/ciclo_comunicacao.png
  docs/_media/images/ciclo_estrela.png
  docs/_media/images/ciclo_mayhew.png
  docs/_media/images/ciclo_objetivos.png
  docs/_media/logo_bce_unb_v3.png
  docs/_media/logos/BCE.jpg
  docs/_media/logos/drive.png
  docs/_media/logos/github.png
  docs/_media/logos/jitsi.png
  docs/_media/logos/telegram.png
  docs/_media/logos/zenhub.png
  docs/_sidebar.md
  docs/escolha_site.md
  docs/index.html
  docs/index.md
  docs/metodologia_do_projeto.md
  docs/planejamento_projeto.md
  docs/processo_design.md
  docs/reunioes/reuniao_2_set_2020.md
  docs/user_profile.md
  mkdocs.yml
Labels: enhancement

#51 Adição do documento de análise de tarefas
  docs/_media/images/AHT_objetivo1.png
  docs/_media/images/AHT_objetivo2.png
  docs/_media/images/goms.png
  docs/pages/ponto_de_controle_2/analise_tarefas.md
  docs/pages/ponto_de_controle_2/perfil_usuario.md
  docs/pages/ponto_de_controle_2/personas.md
  docs/pages/ponto_de_controle_3/general_principles_of_project.md
Labels: documentation

#66 Fix image path
  .github/ISSUE_TEMPLATE/issue_template_meeting.md
  README.md
  docs/README.md
  docs/_media/logos/unb-logo.png
  docs/index.html
  docs/pages/ponto_de_controle_1/apresentacao.md
  docs/pages/ponto_de_controle_1/escolha_site.md
  docs/pages/ponto_de_controle_1/gerenciamento_do_projeto.md
  docs/pages/ponto_de_controle_1/metodologia_do_projeto.md
  docs/pages/ponto_de_controle_1/planejamento_projeto.md
  docs/pages/ponto_de_controle_1/processo_design.md
  docs/pages/ponto_de_controle_2/analise_tarefas.md
  docs/pages/ponto_de_controle_2/perfil_usuario.md
  docs/pages/ponto_de_controle_2/personas.md
  docs/pages/ponto_de_controle_3/principios_gerais.md
  docs/user-profile-research-summary/[TEMPLATE]-relatorio-X-user-profile-search.md
  docs/user-profile-research-summary/relatorio-1-user-profile-search.md
  docs/user-profile-research-summary/relatorio-13-user-profile-search.md
  docs/user-profile-research-summary/relatorio-14-user-profile-search.md
  docs/user-profile-research-summary/relatorio-16-user-profile-search.md
  docs/user-profile-research-summary/relatorio-17-user-profile-search.md
  docs/user-profile-research-summary/relatorio-19-user-profile-search.md
  docs/user-profile-research-summary/relatorio-4-user-profile-search.md
  docs/user-profile-research-summary/relatorio-5-user-profile-search.md
  docs/user-profile-research-summary/relatorio-6-user-profile-search.md
  docs/user-profile-research-summary/relatorio-8-user-profile-search.md
  index.html
Labels: bug-fix

#65 Add caption to images
  docs/_media/assets/images/print_screen/user-profile-reports/user-profile-search-1.1.png
  docs/_media/assets/images/print_screen/user-profile-reports/user-profile-search-1.2.png
  docs/_media/assets/images/print_screen/user-profile-reports/user-profile-search-1.4.png
  docs/_media/assets/images/print_screen/user-profile-reports/user-profile-search-17.2.png
  docs/_media/assets/images/print_screen/user-profile-reports/user-profile-search-17.3.png
  docs/_media/assets/images/print_screen/user-profile-reports/user-profile-search-17.4.png
  docs/_media/assets/images/print_screen/user-profile-reports/user-profile-search-17.6.png
  docs/_media/assets/images/print_screen/user-profile-reports/user-profile-search-17.7.png
  docs/_media/assets/images/print_screen/user-profile-reports/user-profile-search-17.8.png
  docs/_media/assets/images/print_screen/user-profile-reports/user-profile-search-17.9.png
  docs/_media/assets/images/print_screen/user-profile-reports/user-profile-search-19.3.png
  docs/_media/assets/images/print_screen/user-profile-reports/user-profile-search-19.4.png
  docs/_media/assets/images/print_screen/user-profile-reports/user-profile-search-19.5.png
  docs/_media/assets/images/print_screen/user-profile-reports/user-profile-search-5.1.png
  docs/_media/assets/images/print_screen/user-profile-reports/user-profile-search-5.2.png
  docs/_media/assets/images/print_screen/user-profile-reports/user-profile-search-5.3.png
  docs/_media/assets/images/print_screen/user-profile-reports/user-profile-search-5.4.png
  docs/_media/assets/images/print_screen/user-profile-reports/user-profile-search-5.5.png
  docs/_media/assets/images/print_screen/user-profile-reports/user-profile-search-5.6.png
  docs/_media/assets/images/print_screen/user-profile-reports/user-profile-search-5.7.png
  docs/_media/assets/images/print_screen/user-profile-reports/user-profile-search-5.9.png
  docs/_media/assets/images/print_screen/user-profile-reports/user-profile-search-8.3.png
  docs/_media/assets/images/print_screen/user-profile-reports/user-profile-search-8.5.png
  docs/pages/ponto_de_controle_1/gerenciamento_do_projeto.md
  docs/pages/ponto_de_controle_1/metodologia_do_projeto.md
  docs/pages/ponto_de_controle_1/planejamento_projeto.md
  docs/pages/ponto_de_controle_1/processo_design.md
  docs/pages/ponto_de_controle_2/analise_tarefas.md
  docs/pages/ponto_de_controle_2/perfil_usuario.md
  docs/pages/ponto_de_controle_2/personas.md
  docs/user-profile-research-summary/DURVAL/19. PORTAL PERIÓDICOS CAPES: estudo dos não-usuários docentes das IFES brasileiras.pdf
Labels: bug-fix, needs review
