Repository Interacao-Humano-Computador/2020.1-BCE, pull requests merged in 2020-10, with the labels that each got.

#67 Bugfix/design ferramentas
  docs/README.md
  docs/_media/assets/images/equipe/rafaella.jpg
  docs/_media/images/H1_SPTrans.png
  docs/_media/images/H1_sae.png
  docs/_media/images/H2_SPTrans.png
  docs/_media/images/H2_sae.png
  docs/_media/images/H3_SPTrans.png
  docs/_media/images/H3_sae.png
  docs/_media/images/H4_SPTrans.png
  docs/_media/images/H4_sae.png
  docs/_media/images/H5_SPTrans.png
  docs/_media/images/H5_sae.png
  docs/_media/images/H6_SPTrans.png
  docs/_media/images/H6_sae.png
  docs/_media/images/H7_sae.png
  docs/_media/images/H8_sae.png
  docs/_media/images/H9_sae.png
  docs/_media/images/tela1_sae.png
  docs/_media/images/tela2_sae.png
  docs/_media/logos/draw_io.png
  docs/_sidebar.md
  docs/pages/ponto_de_controle_1/apresentacao.md
  docs/pages/ponto_de_controle_1/avaliacoes_sites/avaliacao_SPTrans.md
  docs/pages/ponto_de_controle_1/avaliacoes_sites/avaliacao_bce.md
  docs/pages/ponto_de_controle_1/avaliacoes_sites/avaliacao_sae.md
  docs/pages/ponto_de_controle_1/avaliacoes_sites/avaliacao_zara.md
  docs/pages/ponto_de_controle_1/avaliacoes_sites/planejamento_SPTrans.md
  docs/pages/ponto_de_controle_1/avaliacoes_sites/planejamento_bce.md
  docs/pages/ponto_de_controle_1/avaliacoes_sites/planejamento_sae.md
  docs/pages/ponto_de_controle_1/escolha_site.md
  docs/pages/ponto_de_controle_1/gerenciamento_do_projeto.md
  docs/pages/ponto_de_controle_1/metodologia_do_projeto.md
  docs/pages/ponto_de_controle_1/planejamento_projeto.md
  docs/pages/ponto_de_controle_1/processo_design.md
  docs/pages/ponto_de_controle_2/analise_tarefas.md
  docs/pages/ponto_de_controle_2/guia_de_estilo.md
  docs/pages/ponto_de_controle_2/perfil_usuario.md
  docs/pages/ponto_de_controle_2/personas.md
  docs/pages/ponto_de_controle_3/principios_gerais.md
Labels: bug

#70 Add quiz planning about students profile
  docs/_media/assets/question_ans/ans10.png
  docs/_media/assets/question_ans/ans2.png
  docs/_media/assets/question_ans/ans3.png
  docs/_media/assets/question_ans/ans4.png
  docs/_media/assets/question_ans/ans5.png
  docs/_media/assets/question_ans/ans6.png
  docs/_media/assets/question_ans/ans7.png
  docs/_media/assets/question_ans/ans9.png
  docs/_media/assets/question_ans/ansSN.png
  docs/_sidebar.md
  docs/index.html
  docs/pages/ponto_de_controle_2/perfil_usuario.md
  docs/pages/ponto_de_controle_2/planejamento_do_questionario.md
  index.html
Labels: documentation

#71 Update user profile with quizz data
  docs/_media/assets/images/print_screen/user-profile-reports/acesso-bibliografia-bce-grad.png
  docs/_media/assets/images/print_screen/user-profile-reports/agendamento-de-livro-site-bce-grad.png
  docs/_media/assets/images/print_screen/user-profile-reports/agendamento-de-livro-site-bce-pos.png
  docs/_media/assets/images/print_screen/user-profile-reports/aval-infra-bce-grad.png
  docs/_media/assets/images/print_screen/user-profile-reports/aval-infra-bce.png
  docs/_media/assets/images/print_screen/user-profile-reports/cadastro-ativos-bce.png
  docs/_media/assets/images/print_screen/user-profile-reports/crite-quali-bce.png
  docs/_media/assets/images/print_screen/user-profile-reports/curso-graduandos.png
  docs/_media/assets/images/print_screen/user-profile-reports/curso-pos-graduandos.png
  docs/_media/assets/images/print_screen/user-profile-reports/devolucao-obras-site-bce-grad.png
  docs/_media/assets/images/print_screen/user-profile-reports/devolucao-obras-site-bce-pos.png
  docs/_media/assets/images/print_screen/user-profile-reports/dif_uso_estr_mkt_bce.png
  docs/_media/assets/images/print_screen/user-profile-reports/dispositivo-acesso-BCE-grad.png
  docs/_media/assets/images/print_screen/user-profile-reports/dispositivo-acesso-BCE.png
  docs/_media/assets/images/print_screen/user-profile-reports/distancia-graduandos.png
  docs/_media/assets/images/print_screen/user-profile-reports/distancia-pos-graduandos.png
  docs/_media/assets/images/print_screen/user-profile-reports/experiencia-tecnologias-grad.png
  docs/_media/assets/images/print_screen/user-profile-reports/experiencia-tecnologias-pos-grad.png
  docs/_media/assets/images/print_screen/user-profile-reports/faixa-etaria-graduação.png
  docs/_media/assets/images/print_screen/user-profile-reports/faixa-etaria-pos-graduação.png
  docs/_media/assets/images/print_screen/user-profile-reports/frequencia-uso-site-bce-grad.png
  docs/_media/assets/images/print_screen/user-profile-reports/frequencia-uso-site-bce.png
  docs/_media/assets/images/print_screen/user-profile-reports/genero-graduacao.png
  docs/_media/assets/images/print_screen/user-profile-reports/genero-pos-graduacao.png
  docs/_media/assets/images/print_screen/user-profile-reports/ja-utilizou-site-BCE-grad.png
  docs/_media/assets/images/print_screen/user-profile-reports/ja-utilizou-site-BCE.png
  docs/_media/assets/images/print_screen/user-profile-reports/quali-acerv-bce-2.png
  docs/_media/assets/images/print_screen/user-profile-reports/quali-acerv-bce-grad.png
  docs/_media/assets/images/print_screen/user-profile-reports/quali-acerv-bce.png
  docs/_media/assets/images/print_screen/user-profile-reports/quali-infra-bce-2.png
  docs/_media/assets/images/print_screen/user-profile-reports/quali-servi-bce-2.png
  docs/_media/assets/images/print_screen/user-profile-reports/quali-servi-bce-grad.png
  docs/_media/assets/images/print_screen/user-profile-reports/quali-servi-bce.png
  docs/_media/assets/images/print_screen/user-profile-reports/razoes-nao-uso-bce.png
  docs/_media/assets/images/print_screen/user-profile-reports/tipos-nao-usuario.png
  docs/index.html
  docs/pages/ponto_de_controle_2/perfil_usuario.md
  docs/pages/ponto_de_controle_2/planejamento_do_questionario.md
Labels: documentation

#53 Adiciona Metas de Usabilidade
  docs/_sidebar.md
  docs/pages/ponto_de_controle_3/metas_usabilidade.md
Labels: documentation

#52 Adiciona características da plataforma
  docs/_media/assets/images/dell-server.png
  docs/_media/assets/images/print_screen/browser-support-1.png
  docs/_media/assets/images/print_screen/browser-support-2.png
  docs/_media/assets/images/print_screen/hardware-comp-bce-pcs.png
  docs/_media/assets/images/print_screen/kb_abtn2.png
  docs/_media/assets/images/print_screen/market-share-browser-version.png
  docs/_media/assets/images/print_screen/market-share-browser.png
  docs/_sidebar.md
  docs/pages/ponto_de_controle_3/caracteristicas_da_plataforma.md
Labels: documentation

#86 Add interview planning
  docs/README.md
  docs/_sidebar.md
  docs/pages/ponto_de_controle_2/planejamento_do_questionario.md
  docs/pages/ponto_de_controle_4/planejamento_1_entrevista.md
Labels: documentation, hacktoberfest

#89 Cria documentação para termo de consentimento.
  docs/_sidebar.md
  docs/index.html
  docs/pages/ponto_de_controle_3/apresentacao.md
  docs/pages/ponto_de_controle_4/termo_de_consentimento.md
  docs/pages/ponto_de_controle_4/termo_de_consentimento.pdf
Labels: documentation

#90 Add interviews
  docs/_sidebar.md
  docs/pages/ponto_de_controle_4/entrevistas.md
Labels: documentation, hacktoberfest, needs review

#92 Atualização das referências na Análise de Tarefas
  docs/pages/ponto_de_controle_2/analise_tarefas.md
Labels: bug-fix, documentation

#103 Criação do plano de avaliação do protótipo de baixa fidelidade
  docs/_media/assets/detalhes-sobre-livro.png
  docs/_media/assets/livro-geologia.jpg
  docs/_media/assets/termo-de-consentimento-2.png
  docs/_sidebar.md
  docs/pages/ponto_de_controle_4/plan_aval_prototipo_baixa_fidelidade.md
  docs/pages/ponto_de_controle_5/TERMO DE CONSENTIMENTO Protótipos.pdf
  docs/pages/ponto_de_controle_5/termo_de_consentimento.md
Labels: documentation, hacktoberfest

#93 Feature/63 storyboard
  docs/README.md
  docs/_media/assets/detalhamento-storyboard-1.png
  docs/_media/assets/detalhamento-storyboard-2.png
  docs/_media/assets/storyboard-table-1.png
  docs/_media/images/storyboard_1.png
  docs/_media/images/storyboard_2.png
  docs/_media/images/storyboard_3.png
  docs/_media/images/storyboard_4.png
  docs/_media/logos/storyboardthat_logo.png
  docs/_sidebar.md
  docs/pages/ponto_de_controle_4/storyboard.md
Labels: documentation, hacktoberfest, needs review

#104 Adição da segunda análise de tarefas
  docs/_media/images/AHT_2_objetivo1.png
  docs/_sidebar.md
  docs/pages/ponto_de_controle_4/analise_tarefa_v2.md
  docs/pages/ponto_de_controle_4/entrevistas.md
  docs/pages/ponto_de_controle_4/planejamento_1_entrevista.md
Labels: documentation

#106 Feature/96 planning avaliation storyboard
  docs/_media/assets/termo-de-consentimento-2.png
  docs/_media/assets/termo-de-consentimento-3.png
  docs/_sidebar.md
  docs/pages/ponto_de_controle_4/plan_aval_storyboard.md
  docs/pages/ponto_de_controle_5/termo_de_consentimento.md
Labels: documentation, hacktoberfest, needs review

#109 Feature/83 create low prototype
  docs/README.md
  docs/_media/images/low_fidelity_prototype_1.png
  docs/_media/images/low_fidelity_prototype_10.png
  docs/_media/images/low_fidelity_prototype_11.png
  docs/_media/images/low_fidelity_prototype_12.png
  docs/_media/images/low_fidelity_prototype_13.png
  docs/_media/images/low_fidelity_prototype_14.png
  docs/_media/images/low_fidelity_prototype_15.png
  docs/_media/images/low_fidelity_prototype_16.png
  docs/_media/images/low_fidelity_prototype_17.png
  docs/_media/images/low_fidelity_prototype_18.png
  docs/_media/images/low_fidelity_prototype_19.png
  docs/_media/images/low_fidelity_prototype_2.png
  docs/_media/images/low_fidelity_prototype_3.png
  docs/_media/images/low_fidelity_prototype_4.png
  docs/_media/images/low_fidelity_prototype_5.png
  docs/_media/images/low_fidelity_prototype_6.png
  docs/_media/images/low_fidelity_prototype_7.png
  docs/_media/images/low_fidelity_prototype_8.png
  docs/_media/images/low_fidelity_prototype_9.png
  docs/_media/logos/balsamiq_logo.png
  docs/_sidebar.md
  docs/pages/ponto_de_controle_5/low_fidelity_prototype.md
Labels: documentation, hacktoberfest
